version = "3.7.14"

runner.dialect = scala213

maxColumn = 120

align.preset = none 

indent.main = 4
indent.callSite = 4
indent.defnSite = 4

continuationIndent.callSite = 4
continuationIndent.defnSite = 4

newlines.alwaysBeforeMultilineDef = true